# Generated by Django 3.2 on 2022-12-03 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessreiting',
            name='board_setting',
        ),
        migrations.RemoveField(
            model_name='chessreiting',
            name='figure_setting',
        ),
        migrations.RemoveField(
            model_name='chessreiting',
            name='fon',
        ),
        migrations.RemoveField(
            model_name='chessreiting',
            name='thema',
        ),
        migrations.DeleteModel(
            name='Board_setting',
        ),
        migrations.DeleteModel(
            name='Figure_setting',
        ),
        migrations.DeleteModel(
            name='Fon',
        ),
        migrations.DeleteModel(
            name='Thema',
        ),
    ]
